### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by rafaqz** [lorenzoh/Invariants.jl#4]
These dependencies are a little concerning:

```julia
ANSIColoredPrinters = "a4c015fc-c6ff-483c-b24f-f7ea428134e9"
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"
```

I'm wondering if it's possible to separate out the testing workflow from the invariant declarations (e.g. as a subpackage InvariantTests.jl). Invariant interfaces will be most very useful in extremely light weight base packages, and these deps will be a major source of friction for package devs.

**Comment by lorenzoh** [comment]
Sure! To document:
- `ANSIColoredPrinters`, `AbstractTrees` and `TextWrap` are used exclusively for printing outputs, so they are not needed to define interfaces
- `Markdown` is StdLib
- `InlineTest` is a [1-line file](https://github.com/JuliaTesting/ReTest.jl/blob/master/InlineTest/src/InlineTest.jl) to be able to use  ReTest.jl

Do you happen to have a nightly install with `@time_imports` to check how much of Invariants.jl's import time is self-time and how much comes from these deps?

**Comment by rafaqz** [comment]
Sorry I missed this reply! and I haven't timed the dependencies (I'm not on nightly).

But I'm not sure it will be totally relevant - dependencies also represent the risk of later increases in timing, and various other risks like unwanted version bumps - that tiny base packages will not want to take on.

Best to keep the code for visual checks separate from the declarations.

**Comment by lorenzoh** [comment]
I agree 👍 
I'll create an InvariantsBase.jl package with just the invariants and Boolean check. Anything else that should be in there?

**Comment by lorenzoh** [comment]
https://github.com/lorenzoh/InvariantsCore.jl is the core package with no non-stdlib dependencies

**Comment by rafaqz** [comment]
You can also put it in the Invariants.jl repo to keep it all synced and easy to maintain
